"""
FEATURE: FastAPI app entrypoint - loads all models into memory at startup
(so the first real request isn't slow), registers all route groups.
INSTALLATION: pip install fastapi "uvicorn[standard]"
Run locally with: uvicorn app.main:app --reload --port 8000
Then visit http://localhost:8000/docs for interactive API docs (free,
auto-generated by FastAPI from the Pydantic schemas above).
"""
from contextlib import asynccontextmanager
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from app.models.registry import load_all_models
from app.api.routes import health, predict


@asynccontextmanager
async def lifespan(app: FastAPI):
    load_all_models()
    yield


app = FastAPI(title="SIH ML Service", version="0.1.0", lifespan=lifespan)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # tighten to the Next.js app's real origin in production
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(health.router, prefix="/api/v1", tags=["health"])
app.include_router(predict.router, prefix="/api/v1", tags=["ml"])